name: streamlit
channels:
 - conda-forge

dependencies:
 - bokeh
 - cartopy
 - colorcet
 - graphviz
 - h5py
 - pickle5
 - python-graphviz
 - dask
 - datashader
 - distributed
 - fastparquet
 - holoviews
 - ipython
 - jupyter
 - matplotlib
 - networkx>=2.0
 - numba
 - rmg glibc
 - numpy
 - pandas >=0.24.1
 - param
 - python-snappy
 - python
 - rasterio
 - requests
 - scikit-image
 - seaborn
 - scikit-learn
 - scipy
 - shapely
 - snappy
 - statsmodels
 - streamz
 - xarray
 - ipympl